
/**
 * Kod namjene
 * Enumerations and helper classes
 * Source: PBZ net banking website
 */
export const IntentCodes:Array<{code:string, title:string}> = [
	{code:"ACCT",title:"ACCT (Upravljanje računom)"},
	{code:"ADCS",title:"ADCS (Isplate za donacije, sponzorstva, savjetodavne, intelektualne i druge usluge)"},
	{code:"ADMG",title:"ADMG (Administracija)"},
	{code:"ADVA",title:"ADVA (Predujam)"},
	{code:"AEMP",title:"AEMP (Naknada za zapošljavanje)"},
	{code:"AGRT",title:"AGRT (Poljoprivredni transfer)"},
	{code:"AIRB",title:"AIRB (Zračni)"},
	{code:"ALLW",title:"ALLW (Naknada)"},
	{code:"ALMY",title:"ALMY (Plaćanje alimentacije)"},
	{code:"ANNI",title:"ANNI (Renta)"},
	{code:"ANTS",title:"ANTS (Usluge anestezije)"},
	{code:"AREN",title:"AREN (Knjiženje računa potraživanja)"},
	{code:"BBSC",title:"BBSC (Rodiljna naknada)"},
	{code:"BECH",title:"BECH (Dječji doplatak)"},
	{code:"BENE",title:"BENE (Naknada za nezaposlenost/invaliditet)"},
	{code:"BEXP",title:"BEXP (Poslovni troškovi)"},
	{code:"BLDM",title:"BLDM (Održavanje zgrada)"},
	{code:"BOCE",title:"BOCE (Knjiženje konverzije u Back Office-u)"},
	{code:"BONU",title:"BONU (Novčana nagrada (bonus).)"},
	{code:"BUSB",title:"BUSB (Autobusni)"},
	{code:"CAFI",title:"CAFI (Skrbničke naknade (interne))"},
	{code:"CASH",title:"CASH (Prijenos gotovine)"},
	{code:"CBFF",title:"CBFF (Transakcija se odnosi na kapitalnu štednju, općenito)"},
	{code:"CBFR",title:"CBFR (Transakcija se odnosi na kapitalnu štednju za mirovinu)"},
	{code:"CBLK",title:"CBLK (Masovni kliring kartica)"},
	{code:"CBTV",title:"CBTV (Račun za kabelsku TV)"},
	{code:"CCRD",title:"CCRD (Plaćanje na račun kreditne kartice)"},
	{code:"CDBL",title:"CDBL (Plaćanje računa za kreditnu karticu)"},
	{code:"CDCB",title:"CDCB (Kartično plaćanje uz gotovinski povrat (Cashback))"},
	{code:"CDCD",title:"CDCD (Gotovinska isplata)"},
	{code:"CDCS",title:"CDCS (Isplata gotovine s naknadom)"},
	{code:"CDDP",title:"CDDP (Kartično plaćanje s odgodom)"},
	{code:"CDOC",title:"CDOC (Originalno odobrenje)"},
	{code:"CDQC",title:"CDQC (Zamjenska gotovina)"},
	{code:"CFDI",title:"CFDI (Plaćanje dospjele glavnice)"},
	{code:"CFEE",title:"CFEE (Naknada za poništenje)"},
	{code:"CGDD",title:"CGDD (Direktno terećenje nastalo kao rezultat kartične transakcije)"},
	{code:"CHAR",title:"CHAR (Dobrotvorno plaćanje)"},
	{code:"CLPR",title:"CLPR (Otplata glavnice kredita za automobil)"},
	{code:"CMDT",title:"CMDT (Plaćanje roba)"},
	{code:"COLL",title:"COLL (Naplata)"},
	{code:"COMC",title:"COMC (Komercijalno plaćanje)"},
	{code:"COMM",title:"COMM (Provizija)"},
	{code:"COMT",title:"COMT (Konsolidirano plaćanje treće strane za račun potrošača.)"},
	{code:"COST",title:"COST (Troškovi)"},
	{code:"CPKC",title:"CPKC (Troškovi parkiranja)"},
	{code:"CPYR",title:"CPYR (Autorsko pravo)"},
	{code:"CSDB",title:"CSDB (Gotovinska isplata)"},
	{code:"CSLP",title:"CSLP (Isplata socijalnih zajmova društava  banci)"},
	{code:"CVCF",title:"CVCF (Ustanova za usluge skrbi za rekonvalescente)"},
	{code:"DBTC",title:"DBTC (Naplata putem terećenja)"},
	{code:"DCRD",title:"DCRD (Plaćanje na račun debitne kartice.)"},
	{code:"DEPT",title:"DEPT (Depozit)"},
	{code:"DERI",title:"DERI (Derivati (izvedenice))"},
	{code:"DIVD",title:"DIVD (Dividenda)"},
	{code:"DMEQ",title:"DMEQ (Trajna medicinska pomagala)"},
	{code:"DNTS",title:"DNTS (Zubarske usluge)"},
	{code:"EDUC",title:"EDUC (Troškovi školovanja)"},
	{code:"ELEC",title:"ELEC (Račun za električnu energiju)"},
	{code:"ENRG",title:"ENRG (Energenti)"},
	{code:"ESTX",title:"ESTX (Porez na ostavštinu)"},
	{code:"ETUP",title:"ETUP (Doplata e-novca)"},
	{code:"FAND",title:"FAND (Isplata naknade za elementarne nepogode)"},
	{code:"FCOL",title:"FCOL (Naplata naknade po kartičnoj transakciji)"},
	{code:"FCPM",title:"FCPM (Zakašnjele naknade)"},
	{code:"FERB",title:"FERB (Trajektni)"},
	{code:"FREX",title:"FREX (Devizno tržište)"},
	{code:"FWLV",title:"FWLV (Porez na strane radnike)"},
	{code:"GASB",title:"GASB (Račun za plin)"},
	{code:"GDDS",title:"GDDS (Kupovina-prodaja roba)"},
	{code:"GDSV",title:"GDSV (Kupovina/prodaja roba i usluga)"},
	{code:"GFRP",title:"GFRP (Naknada za nezaposlene u toku stečaja)"},
	{code:"GOVI",title:"GOVI (Državno osiguranje)"},
	{code:"GOVT",title:"GOVT (Plaćanje države)"},
	{code:"GSCB",title:"GSCB (Kupovina-prodaja roba i usluga uz gotovinski povrat)"},
	{code:"GSTX",title:"GSTX (Porez na robu i usluge)"},
	{code:"GVEA",title:"GVEA (Austrijski državni zaposlenici, Kategorija A)"},
	{code:"GVEB",title:"GVEB (Austrijski državni zaposlenici, Kategorija B)"},
	{code:"GVEC",title:"GVEC (Austrijski državni zaposlenici, Kategorija C)"},
	{code:"GVED",title:"GVED (Austrijski državni zaposlenici, Kategorija D)"},
	{code:"GWLT",title:"GWLT (Isplata žrtvama rata i invalidima)"},
	{code:"HEDG",title:"HEDG (Omeđivanje rizika (Hedging))"},
	{code:"HLRP",title:"HLRP (Otplata stambenog kredita)"},
	{code:"HLTC",title:"HLTC (Kućna njega bolesnika)"},
	{code:"HLTI",title:"HLTI (Zdravstveno osiguranje)"},
	{code:"HREC",title:"HREC (Transakcija se odnosi na doprinos poslodavca za troškove stanovanja)"},
	{code:"HSPC",title:"HSPC (Bolnička njega)"},
	{code:"HSTX",title:"HSTX (Porez na stambeni prostor)"},
	{code:"ICCP",title:"ICCP (Neopozivo plaćanje sa računa kreditne kartice)"},
	{code:"ICRF",title:"ICRF (Ustanova socijalne skrbi)"},
	{code:"IDCP",title:"IDCP (Neopozivo plaćanje sa računa debitne kartice)"},
	{code:"IHRP",title:"IHRP (Plaćanje rate pri kupnji na otplatu)"},
	{code:"INPC",title:"INPC (Premija osiguranja za vozilo)"},
	{code:"INSM",title:"INSM (Rata)"},
	{code:"INSU",title:"INSU (Premija osiguranja)"},
	{code:"INTC",title:"INTC (Plaćanje unutar društva)"},
	{code:"INTE",title:"INTE (Kamata)"},
	{code:"INTX",title:"INTX (Porez na dohodak)"},
	{code:"INVS",title:"INVS (Plaćanje za fondove i vrijednosnice)"},
	{code:"IVPT",title:"IVPT (Plaćanje računa)"},
	{code:"LBRI",title:"LBRI (Osiguranje iz rada)"},
	{code:"LICF",title:"LICF (Naknada za licencu)"},
	{code:"LIFI",title:"LIFI (Životno osiguranje)"},
	{code:"LIMA",title:"LIMA (Upravljanje likvidnošću)"},
	{code:"LOAN",title:"LOAN (Zajam)"},
	{code:"LOAR",title:"LOAR (Otplata zajma)"},
	{code:"LTCF",title:"LTCF (Ustanova dugoročne zdravstvene skrbi)"},
	{code:"MDCS",title:"MDCS (Medicinske usluge)"},
	{code:"MSVC",title:"MSVC (Višestruke vrste usluga)"},
	{code:"MTUP",title:"MTUP (Doplata mobilnog uređaja (bon))"},
	{code:"NETT",title:"NETT (Saldiranje (netiranje))"},
	{code:"NITX",title:"NITX (Porez na neto dohodak)"},
	{code:"NOWS",title:"NOWS (Nenavedeno)"},
	{code:"NWCH",title:"NWCH (Troškovi za mrežu)"},
	{code:"NWCM",title:"NWCM (Mrežna komunikacija)"},
	{code:"OFEE",title:"OFEE (Početna naknada (Opening Fee))"},
	{code:"OTHR",title:"OTHR (Ostalo)"},
	{code:"OTLC",title:"OTLC (Račun za ostale telekom usluge)"},
	{code:"PADD",title:"PADD (Izravno terećenje)"},
	{code:"PAYR",title:"PAYR (Obračun plaća)"},
	{code:"PENO",title:"PENO (Prisilna naplata)"},
	{code:"PENS",title:"PENS (Plaćanje mirovine)"},
	{code:"PHON",title:"PHON (Telefonski račun)"},
	{code:"POPE",title:"POPE (Knjiženje mjesta kupnje)"},
	{code:"PPTI",title:"PPTI (Osiguranje imovine)"},
	{code:"PRCP",title:"PRCP (Plaćanje cijene)"},
	{code:"PRME",title:"PRME (Plemeniti metali)"},
	{code:"PTSP",title:"PTSP (Uvjeti plaćanja)"},
	{code:"PTXP",title:"PTXP (Porez na imovinu)"},
	{code:"RCKE",title:"RCKE (Knjiženje ponovne prezentacije čeka)"},
	{code:"RCPT",title:"RCPT (Plaćanje blagajničke potvrde. (ReceiptPayment))"},
	{code:"RDTX",title:"RDTX (Cestarina)"},
	{code:"REBT",title:"REBT (Plaćanje popusta/rabata)"},
	{code:"REFU",title:"REFU (Povrat)"},
	{code:"RENT",title:"RENT (Najam)"},
	{code:"RHBS",title:"RHBS (Isplata za vrijeme profesionalne rehabilitacije)"},
	{code:"RIMB",title:"RIMB (Povrat prethodne pogrešne transakcije)"},
	{code:"RINP",title:"RINP (Plaćanje rata koje se ponavljaju)"},
	{code:"RLWY",title:"RLWY (Željeznički)"},
	{code:"ROYA",title:"ROYA (Tantijeme)"},
	{code:"SALA",title:"SALA (Plaćanje plaće)"},
	{code:"SAVG",title:"SAVG (Štednja)"},
	{code:"SCVE",title:"SCVE (Kupovina/prodaja usluga)"},
	{code:"SECU",title:"SECU (Vrijednosni papiri)"},
	{code:"SEPI",title:"SEPI (Kupnja vrijednosnica (interna))"},
	{code:"SSBE",title:"SSBE (Naknada socijalnog osiguranja)"},
	{code:"STDY",title:"STDY (Studiranje)"},
	{code:"SUBS",title:"SUBS (Pretplata)"},
	{code:"SUPP",title:"SUPP (Plaćanje dobavljača)"},
	{code:"TAXR",title:"TAXR (Povrat poreza)"},
	{code:"TAXS",title:"TAXS (Plaćanje poreza)"},
	{code:"TBIL",title:"TBIL (Troškovi telekomunikacija)"},
	{code:"TCSC",title:"TCSC (Gradske naknade)"},
	{code:"TELI",title:"TELI (Transakcija inicirana telefonom)"},
	{code:"TRAD",title:"TRAD (Trgovinske usluge)"},
	{code:"TREA",title:"TREA (Plaćanje riznice)"},
	{code:"TRFD",title:"TRFD (Zaklada)"},
	{code:"TRPT",title:"TRPT (Prepaid cestarina (ENC))"},
	{code:"UBIL",title:"UBIL (Komunalne usluge)"},
	{code:"VATX",title:"VATX (Plaćanje poreza na dodatnu vrijednost)"},
	{code:"VIEW",title:"VIEW (Usluge oftalmološke skrbi)"},
	{code:"WEBI",title:"WEBI (Transakcija inicirana internetom)"},
	{code:"WHLD",title:"WHLD (Porez po odbitku)"},
	{code:"WTER",title:"WTER (Račun za vodu)"}
]
