/**
 * TODO: Add validation rules for every payment model
 * Source: FINA website - http://www.fina.hr/fgs.axd?id=16090&usg=AFQjCNF8XEhnL9POBo5CccBjCWW9gzBJJg&sig2=b5VcZvu4wgv185jhJR-U_w&cad=rja
 */
export const PaymentModels:Array<{model:string}> = [
		{ model: "HR00" },
		{ model: "HR01" },
		{ model: "HR02" },
		{ model: "HR03" },
		{ model: "HR04" },
		{ model: "HR05" },
		{ model: "HR06" },
		{ model: "HR07" },
		{ model: "HR08" },
		{ model: "HR09" },
		{ model: "HR10" },
		{ model: "HR11" },
		{ model: "HR12" },
		{ model: "HR13" },
		{ model: "HR14" },
		{ model: "HR15" },
		{ model: "HR16" },
		{ model: "HR17" },
		{ model: "HR18" },
		{ model: "HR23" },
		{ model: "HR24" },
		{ model: "HR26" },
		{ model: "HR27" },
		{ model: "HR28" },
		{ model: "HR29" },
		{ model: "HR30" },
		{ model: "HR31" },
		{ model: "HR33" },
		{ model: "HR34" },
		{ model: "HR40" },
		{ model: "HR41" },
		{ model: "HR42" },
		{ model: "HR43" },
		{ model: "HR55" },
		{ model: "HR62" },
		{ model: "HR63" },
		{ model: "HR64" },
		{ model: "HR65" },
		{ model: "HR67" },
		{ model: "HR68" },
		{ model: "HR69" },
		{ model: "HR99" },
		{ model: "HR25" },
		{ model: "HR83" },
		{ model: "HR84" },
		{ model: "HR50" }
	]