/**
 * TODO: Add validation rules for every payment model
 * Source: FINA website - http://www.fina.hr/fgs.axd?id=16090&usg=AFQjCNF8XEhnL9POBo5CccBjCWW9gzBJJg&sig2=b5VcZvu4wgv185jhJR-U_w&cad=rja
 */
export const PaymentModels:Array<{model:string}> = [
		{ model: "00" },
		{ model: "01" },
		{ model: "02" },
		{ model: "03" },
		{ model: "04" },
		{ model: "05" },
		{ model: "06" },
		{ model: "07" },
		{ model: "08" },
		{ model: "09" },
		{ model: "10" },
		{ model: "11" },
		{ model: "12" },
		{ model: "13" },
		{ model: "14" },
		{ model: "15" },
		{ model: "16" },
		{ model: "17" },
		{ model: "18" },
		{ model: "23" },
		{ model: "24" },
		{ model: "26" },
		{ model: "27" },
		{ model: "28" },
		{ model: "29" },
		{ model: "30" },
		{ model: "31" },
		{ model: "33" },
		{ model: "34" },
		{ model: "40" },
		{ model: "41" },
		{ model: "42" },
		{ model: "43" },
		{ model: "55" },
		{ model: "62" },
		{ model: "63" },
		{ model: "64" },
		{ model: "65" },
		{ model: "67" },
		{ model: "68" },
		{ model: "69" },
		{ model: "99" },
		{ model: "25" },
		{ model: "83" },
		{ model: "84" },
		{ model: "50" }
	]